Persona: default

OnTheFly: true
SaveMemory: true

Logging:
  folder: ./Logs
  wipe_logs_on_start: true
  general: error
  modelio: debug
  results: info

Paths:
  Files: ./Files
  Workspace: ./Workspace