# This file works as a knowledge base for the system persona,
# Any attribute in this file will be automatically loaded as part of the agent data for prompt rendering
Name: BotName

Description: |+
    Bot description here

# ... other attributes ...
